# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-05 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=30)),
                ('times', models.IntegerField()),
                ('query_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
