# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-05 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='key_word',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
