# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-05 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_test', '0002_auto_20170405_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='key_word',
            field=models.CharField(max_length=30),
        ),
    ]
