# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-21 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_comment_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.CharField(max_length=30, null=True, verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=30, null=True, verbose_name='用户'),
        ),
    ]
